app = "termchat-server-al"
primary_region = "ewr"

[build]
  dockerfile = "Dockerfile"
  target = "server"

[env]
  TERMCHAT_ADDR = ":8080"
  TERMCHAT_PATH = "/join"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    hard_limit = 25
    soft_limit = 20

[[vm]]
  size = "shared-cpu-1x"
  memory = "256"
